# -*- coding: utf-8 -*-
"""Untitled2.ipynb의 사본

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16QzwElWE8WZZki9KurJnASrvt9JJ8lS6
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
from datetime import datetime

# 1. 정보 수집 함수 정의
def get_finance_data():
    url = "https://finance.naver.com/marketindex/"
    res = requests.get(url)
    soup = BeautifulSoup(res.text, 'html.parser')

    # 데이터 추출
    usd_rate = soup.select_one('div.head_info > span.value').text # 환율
    kospi_index = soup.select_one('span.num_quot > #now_value').text if soup.select_one('#now_value') else "데이터없음"

    # 코스피를 다른 경로에서 가져오기 (만약 위 경로가 안될 경우)
    kospi_url = "https://finance.naver.com/sise/"
    res_k = requests.get(kospi_url)
    soup_k = BeautifulSoup(res_k.text, 'html.parser')
    kospi_index = soup_k.select_one('#KOSPI_now').text

    # 현재 시간 기록
    now = datetime.now().strftime('%Y-%m-%d %H:%M:%S')

    return {
        "수집시간": now,
        "미국(USD)": usd_rate,
        "코스피(KOSPI)": kospi_index
    }

# 2. 실행 및 저장
data = get_finance_data()
df = pd.DataFrame([data])

# 기존에 파일이 있으면 이어서 붙이고, 없으면 새로 생성 (A 버튼 클릭 효과)
file_name = 'finance_data_log.xlsx'
try:
    existing_df = pd.read_excel(file_name)
    df = pd.concat([existing_df, df], ignore_index=True)
except FileNotFoundError:
    pass

df.to_excel(file_name, index=False)
print(f"저장 완료: {data}")
